[versions]
binary-compatibility-validator = "0.18.1"
dokka = "2.1.0"
kotlin = "2.3.10"
kover = "0.9.5"
publish-plugin = "0.36.0"
versions-plugin = "0.53.0"
ktfmt-plugin = "0.25.0"

[libraries]
# Plugins specified in buildSrc/build.gradle.kts
binary-compatibility-validator-plugin = { module = "org.jetbrains.kotlinx.binary-compatibility-validator:org.jetbrains.kotlinx.binary-compatibility-validator.gradle.plugin", version.ref = "binary-compatibility-validator" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradle-versions-plugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versions-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kover-gradle-plugin = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
vanniktech-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish-plugin" }
ktfmt-gradle-plugin = { module = "com.ncorti.ktfmt.gradle:com.ncorti.ktfmt.gradle.gradle.plugin", version.ref = "ktfmt-plugin" }

# Libraries
funfix-tasks-jvm = { module = "org.funfix:tasks-jvm", version = "0.4.0" }
hikaricp = { module = "com.zaxxer:HikariCP", version = "7.0.2" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.27" }
jdbc-hsqldb = { module = "org.hsqldb:hsqldb", version = "2.7.4" }
jdbc-sqlite = { module = "org.xerial:sqlite-jdbc", version = "3.51.1.0" }
jdbc-mssql = { module = "com.microsoft.sqlserver:mssql-jdbc", version = "12.4.2.jre11" }
jdbc-mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version = "3.5.3" }
jdbc-postgresql = { module = "org.postgresql:postgresql", version = "42.7.7" }
junit-bom = { module = "org.junit:junit-bom", version = "6.0.2" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version = "2.0.3" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version = "1.21.4" }
testcontainers-mssqlserver = { module = "org.testcontainers:testcontainers-mssqlserver" }
testcontainers-mariadb = { module = "org.testcontainers:testcontainers-mariadb" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
