name: Build

on:
  push:
    branches: [ main ]
    tags:
    - 'v*.*.*'
  pull_request:

jobs:
  test-gradle:
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: unix:///var/run/docker.sock
      TESTCONTAINERS_HOST_OVERRIDE: localhost
      TESTCONTAINERS_RYUK_DISABLED: "true"
    strategy:
      fail-fast: false
      matrix:
        java-version: ['21', '25']
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          cache: 'gradle'
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          # cache-dependency-path: |
          #   ./**/*.gradle.kts
          #   ./gradle/wrapper/gradle-wrapper.properties
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Docker Info
        run: docker info
      - name: Test
        run: ./gradlew check --no-daemon
      - name: Upload Results
        uses: actions/upload-artifact@v5
        if: always() # This ensures that test results are uploaded even if the test step fails
        with:
          name: test-results-${{ matrix.java-version }}
          path: |
            **/build/reports/
            **/build/test-results/

  test-sbt:
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: unix:///var/run/docker.sock
      TESTCONTAINERS_HOST_OVERRIDE: localhost
      TESTCONTAINERS_RYUK_DISABLED: "true"
    strategy:
      fail-fast: false
      matrix:
        java-version: ['21', '25']
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          cache: 'sbt'
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Docker Info
        run: docker info
      - name: Test (SBT)
        run: ./sbt ci-test
      - name: Upload Results
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: test-results-sbt-${{ matrix.java-version }}
          path: |
            **/target/test-reports/
            **/target/streams/test/
            **/target/scalafmt/
