name: Publish Release for Scala

on: workflow_dispatch

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - run: ./sbt ci-publish
        env:
          # For gradle
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GRADLE_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GRADLE_SIGNING_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GRADLE_SIGNING_KEY }}
          # For sbt
          PGP_KEY_ID: ${{ secrets.SBT_PGP_KEY_ID }}
          PGP_PASSPHRASE: ${{ secrets.SBT_PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.SBT_PGP_SECRET }}
          # SBT_PGP_USE_GPG: false
          SONATYPE_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          BUILD_RELEASE: true
